apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "fullname" . }}
  annotations:
    "kubernetes.io/ingress.class": "traefik"
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ template "hostname" .Values.service.url }}`) && PathPrefix(`/guild`)
    kind: Rule
    services:
    - name: {{ template "fullname" . }}
      port: {{ .Values.service.externalPort }}
