apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "fullname" . }}
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ template "hostname" .Values.service.url }}`) && PathPrefix(`{{ .Values.ingress.path | default "/" }}`)
    kind: Rule
    services:
    - name: {{ template "fullname" . }}
      port: {{ .Values.service.externalPort }}
